### PR TITLE
Rewritten to use AI agent

### PR DESCRIPTION
**Pull request by JamesPerisher**
- Rewrote most of it to use an AI agent capable of tool use for additional functionality
- moved config into .env file
-  Extended .gitignore for standard python ignore files
- Added requirements.txt file for better requirement management

A lot of it was Based off of https://github.com/langchain-ai/langchain/tree/master/templates/neo4j-semantic-ollama 

I only tested with Chatgpt-3.5-turbo as model cos it was easier to set up.

Would also like to request a GPLv3 license be added to the project.

### CODE REVIEW

**Comment by sidgames5** [comment]
When running your code I received an error:
```
Traceback (most recent call last):
  File "/home/sid/excalibur/main.py", line 13, in <module>
    from agent import agent_executor
  File "/home/sid/excalibur/agent.py", line 24, in <module>
    base_url=os.environ["OLLAMA_BASE_URL"],
             ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 679, in __getitem__
KeyError: 'OLLAMA_BASE_URL'
```
Here is the .env file:
```
VOSK_MODEL_PATH="/home/sid/Documents/code/python/voice-assistant/vosk/vosk-model-en-us-0.42-gigaspeech/"
WAKE_WORD="hey excalibur"
AI_MODEL="mistral"
CLOCK_24_HOURS=true
UNITS_IMPERIAL=false
WEATHER_STATION="KAGC"
OLLAMA_BASE_URL=http://localhost:11434
```
I did run `ollama serve` in another terminal.

**Comment by JamesPerisher** [comment]
Ok couple things u can do either add this module and code: 
```python
from dotenv import load_dotenv
load_dotenv()
```

Or run `source .env` in your terminal before running the program.

If ur using vscode u can set it to load via "envFile": "${workspaceFolder}/.env" in your launch profile in the launch.json file. Im sure other ides have simmillar functionality as well.


Or alternativly u can wait till i fix it tommorrow.

**Comment by sidgames5** [comment]
The code now works however it is super slow (horrendously slow compared to what was previously going on). I asked for the weather and after it finished processing it gave this error:
```
> Entering new AgentExecutor chain...
 Question: What's the weather?
Thought: I need to retrieve the current weather information for the user's location. I will use the Weather tool for this.
Action:```json
{
    "action": "Weather",
    "action_input": {}
}
```Traceback (most recent call last):
  File "/home/sid/excalibur/main.py", line 63, in <module>
    main()
  File "/home/sid/excalibur/main.py", line 59, in main
    say(send_to_ai(result[len(os.environ.get("WAKE_WORD")):]))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sid/excalibur/main.py", line 18, in send_to_ai
    return agent_executor.invoke({"input": content})["output"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sid/.local/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 4219, in invoke
    return self.bound.invoke(
           ^^^^^^^^^^^^^^^^^^
  File "/home/sid/.local/lib/python3.11/site-packages/langchain/chains/base.py", line 163, in invoke
    raise e
  File "/home/sid/.local/lib/python3.11/site-packages/langchain/chains/base.py", line 153, in invoke
    self._call(inputs, run_manager=run_manager)
  File "/home/sid/.local/lib/python3.11/site-packages/langchain/agents/agent.py", line 1432, in _call
    next_step_output = self._take_next_step(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/sid/.local/lib/python3.11/site-packages/langchain/agents/agent.py", line 1138, in _take_next_step
    [
  File "/home/sid/.local/lib/python3.11/site-packages/langchain/agents/agent.py", line 1138, in <listcomp>
    [
  File "/home/sid/.local/lib/python3.11/site-packages/langchain/agents/agent.py", line 1223, in _iter_next_step
    yield self._perform_agent_action(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sid/.local/lib/python3.11/site-packages/langchain/agents/agent.py", line 1245, in _perform_agent_action
    observation = tool.run(
                  ^^^^^^^^^
  File "/home/sid/.local/lib/python3.11/site-packages/langchain_core/tools.py", line 382, in run
    raise e
  File "/home/sid/.local/lib/python3.11/site-packages/langchain_core/tools.py", line 373, in run
    parsed_input = self._parse_input(tool_input)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sid/.local/lib/python3.11/site-packages/langchain_core/tools.py", line 280, in _parse_input
    result = input_args.parse_obj(tool_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pydantic/v1/main.py", line 526, in parse_obj
    return cls(**obj)
           ^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for WeatherInput
location_code
  field required (type=value_error.missing)
```

**Comment by JamesPerisher** [comment]
Seems like your model isn't suited to working as a json agent, try the mistral instruct model it might do better idk. Works perfectly with chatgpt tho. Is it slow as in time till response starts talking or slow as in time till first token generated in the log, if its the latter that's a compute problem as a result of a larger prompt and limited compute resources. 

I'm not going to do anymore work on this I have other things to work on, I recommend do some input validation and make it try again instead of crashing liek above. The slow response thing not a whole lot can be done without a production gpu and optimized model.

**Comment by sidgames5** [comment]
I will try that but for now I am not going to merge this since there are a ton of conflicts. I may revisit this PR in the future.

**Pull request closed without merging**
